#name of workflow
name: first

on: push

jobs: 
    job1: 
      name: First Job
      runs-on: ubuntu-latest
      steps: 
      - name: Job 1
        uses: actions/checkout@v2
      - name: Job 2 
        run: env | sort
    job2: 
      name: Second Job
      runs-on: windows-latest
      steps: 
      - name: Job 1
        uses: actions/checkout@v2
      - name: Job 2 
        run: "Get-ChildItem Env: | Sort-Object Name"